<HomePage>:
    MDBoxLayout:
        size_hint_y:.25
        MDBoxLayout:
            orientation:"vertical"
            MDLabel:
                text: "Welcome to the Home Page"
                halign: "center"
                font_style: "H4"

            MDRaisedButton:
                text: "Go to Settings"
                pos_hint: {"center_x": 0.5}
                on_release: app.root.current = 'settings'

